export const images = [
  {
    id: 1,
    titre: "Tres-Zap",
    desc: "Ardea cinerea",
    theme: "Durango",
    src: "/Images/img01.jpg",
  },

  {
    id: 2,
    titre: "It",
    desc: "Falco mexicanus",
    theme: "Crown Victoria",
    src: "/Images/img02.jpg",
  },
  {
    id: 3,
    titre: "Span",
    desc: "Lasiodora parahybana",
    theme: "Sierra 3500",
    src: "/Images/img03.jpg",
  },
  {
    id: 4,
    titre: "Aerified",
    desc: "Leptoptilos crumeniferus",
    theme: "Ascender",
    src: "/Images/img04.jpg",
  },
  {
    id: 5,
    titre: "Mat Lam Tam",
    desc: "Panthera pardus",
    theme: "9000",
    src: "/Images/img05.jpg",
  },
  {
    id: 6,
    titre: "It",
    desc: "Turtur chalcospilos",
    theme: "Sierra 3500",
    src: "/Images/img06.jpg",
  },
  {
    id: 7,
    titre: "Overhold",
    desc: "Graspus graspus",
    theme: "Charger",
    src: "/Images/img07.jpg",
  },
  {
    id: 8,
    titre: "Prodder",
    desc: "Ratufa indica",
    theme: "Tercel",
    src: "/Images/img08.jpg",
  },
  {
    id: 9,
    titre: "Bigtax",
    desc: "Echimys chrysurus",
    theme: "M5",
    src: "/Images/img09.jpg",
  },
  {
    id: 10,
    titre: "Voltsillam",
    desc: "Papio cynocephalus",
    theme: "M5",
    src: "/Images/img10.jpg",
  },
];
